name: wireframe_theme_flutter
description: FLUX_WIREFRAME – A professional wireframe theme package for building structural UI prototypes in Flutter.
version: 1.0.1
repository: https://github.com/GLLB-Apps/wireframe_theme_flutter

environment:
  sdk: ^3.6.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # Om du har specifika typsnitt för wireframe-looken (t.ex. en "handwritten" font), 
  # deklarerar du dem här.